### ISSUE TITLE
Getting exception : Could not find or load main class se.lth.cs.srl.CompletePipeline

### ISSUE THREAD

**Issue by nandinicbit1981** [microth/mateplus#4]
I'm getting this error when i run "sh parse.sh" command
To compile this project, there is no pom.xml in the root of the project.
How do i compile this?

**Comment by microth** [comment]
You need to download all dependencies and then compile the java source files via javac.

**Comment by mosynaq** [comment]
I am not a Java developer but as a thesis topic I have to use mateplus. In the previous post it is said that 

> You need to download all dependencies and then compile the java source files via javac.

I have downloaded all libs and models but I do not know how to compile source files via javac. Can any one please give me some instructions on this issue? Just issuing `javac src/Demo.java` or `javac src/FramatDemo.java` returns a page of error!

**Comment by microth** [comment]
You need to add the libraries that you downloaded to your classpath. You can do this via the parameter "-cp library1:library2:...". Also, please make sure that you run javac in the source file directory. Otherwise, javac will interpret the directory name "src" as a package name. For further help on compiling java source files, please also consider help from a java forum.
